apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "destination-rule.fullname" . }}
spec:
  host: {{ .Values.host }}
  subsets:
  - name: {{ .Values.current.version }}
    labels:
      version: {{ .Values.current.version }}
  - name: {{ .Values.new.version }}
    labels:
      version: {{ .Values.new.version }}