apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "gateway.fullname" . }}-vs
spec:
  hosts:
  - "{{ .Values.current.requestHost }}"
  - "{{ .Values.new.requestHost }}"
  gateways:
  - {{ template "gateway.fullname" . }}
  http:
  - match:
    - authority:
        exact: {{ .Values.new.requestHost }}
    route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.new.version }}
  - route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.current.version }}
      weight: {{ .Values.current.weight }}
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.new.version }}
      weight: {{ .Values.new.weight }}
