apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "gateway.fullname" . }}-vs
spec:
  hosts:
  - "*"
  gateways:
  - {{ template "gateway.fullname" . }}
  http:
  - route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.current.version }}
