apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "gateway.fullname" . }}-vs
spec:
  hosts:
  - "{{ .Values.master.requestHost }}"
  - "{{ .Values.canary.requestHost }}"
  gateways:
  - {{ template "gateway.fullname" . }}
  http:
  - match:
    - authority:
        exact: {{ .Values.canary.requestHost }}
    route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.canary.version }}
  - route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.master.version }}
      weight: {{ .Values.master.weight }}
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.canary.version }}
      weight: {{ .Values.canary.weight }}
