apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "circuit-breaking.fullname" . }}
spec:
  host: {{ .Values.host }}
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: {{ .Values.maxConnections }}
      http:
        http1MaxPendingRequests: {{ .Values.http1MaxPendingRequests }}
        http2MaxRequests: {{ .Values.http2MaxRequests }}
        maxRequestsPerConnection: {{ .Values.maxRequestsPerConnection }}
    outlierDetection:
      consecutiveErrors: {{ .Values.consecutiveErrors }}
      interval: {{ .Values.interval }}s
      baseEjectionTime: {{ .Values.baseEjectionTime }}s
      maxEjectionPercent: {{ .Values.maxEjectionPercent }}