apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "request-routing.fullname" . }}
spec:
  hosts:
  - {{ .Values.host }}
  http:
  - route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.current.version }}