apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "mirroring.fullname" . }}
spec:
  hosts:
    - {{ .Values.host }}
  http:
  - route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.current.version }}
      weight: {{ .Values.current.weight }}
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.new.version }}
      weight: {{ .Values.new.weight }}
