apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "traffic-shifting.fullname" . }}
spec:
  hosts:
  - {{ .Values.host }}
  http:
  - match:
    - headers:
        cookie:
          regex: "^(.*?;)?({{ .Values.cookie }})(;.*)?$"
    route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.canary.version }}
  - route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.master.version }}
      weight: {{ .Values.master.weight }}
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.canary.version }}
      weight: {{ .Values.canary.weight }}