apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "traffic-shifting.fullname" . }}
spec:
  hosts:
    - {{ .Values.host }}
  http:
  - route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.current.version }}
      weight: {{ .Values.current.weight }}
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.canary.version }}
      weight: {{ .Values.canary.weight }}
