apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.host }}
spec:
  hosts:
    - {{ .Values.host }}
  http:
  - fault:
      delay:
        fixedDelay: {{ .Values.fixedDelay }}s
        percent: {{ .Values.percent }}
    route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.version }}