apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "timeouts.fullname" . }}
spec:
  host: {{ .Values.host }}
  subsets:
  - name: {{ .Values.version }}
    labels:
      version: {{ .Values.version }}