apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.host }}
spec:
  hosts:
    - {{ .Values.host }}
  http:
  - route:
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.currentVersion }}
      weight: {{ .Values.currentVersionWeight }}
    - destination:
        host: {{ .Values.host }}
        subset: {{ .Values.newVersion }}
      weight: {{ .Values.newVersionWeight }}
